output: "{{.Dir}}/README.md"
format: github
repository:
  url: https://github.com/SuperBuker/terraform-provider-dns-he-net/tree/master/internal/resources
  defaultBranch: master
  directory: .
includeUnexported: true
