name: Golang

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.x' ] # To extend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod download

    - name: Run linter
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.52.0

    - name: Run go vet
      run: go vet ./...

    - name: Unit tests
      run: |
        go test -v  ./... -covermode count -coverprofile coverage.out -json > TestResults-${{ matrix.go-version }}.json
        go tool cover -func coverage.out

    #- name: Build
    #  run: go build -v ./...
    
    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json