name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    #timeout-minutes: TBD
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.0.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  goreportcard:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Update Go Report Card
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
        run: |
          GITHUB_DOMAIN="${GITHUB_SERVER_URL#*/}"
          curl 'https://goreportcard.com/checks' \
          -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
          --data-urlencode "repo=${GITHUB_DOMAIN}/${GITHUB_REPOSITORY}" \
          --compressed
